lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-tractoflow_logo_light.png
  - docs/images/nf-core-tractoflow_logo_light.png
  - docs/images/nf-core-tractoflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - conf/igenomes.config
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-tractoflow_logo_light.png
  - docs/images/nf-core-tractoflow_logo_light.png
  - docs/images/nf-core-tractoflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: '@AlexVCaron'
  description: Human diffusion MRI processing and tractography
  force: false
  is_nfcore: false
  name: tractoflow
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - slackreport
    - seqera_platform
  version: 1.0dev
