---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "preproc_gibbs"
description: Remove Gibbs Ringing Artifacts
keywords:
  - correction
  - Gibbs
  - artefact

tools:
  - "MRtrix3":
      description: "Toolbox for image processing, analysis and visualisation of dMRI."
      homepage: "https://mrtrix.readthedocs.io/en/latest/"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi:
      type: file
      description: Nifti image file to correct
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi:
      type: file
      description: DWI image Gibbs corrected
      pattern: "*.{nii,nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@arnaudbore"
